### ISSUE TITLE
Declare as a Web Component

### ISSUE THREAD

**Issue by aress31** [GoogleChromeLabs/dark-mode-toggle#39]
Hi GoogleChromeLabs,

I am no expert in web dev or web components, but in my current project when using the `dark-mode-toggle`, lit-plugin is throwing the following warning message:

```
Unknown tag <dark-mode-toggle>.
  Check that you've imported the element, and that it's declared on the HTMLElementTagNameMap. If it can't be imported, consider adding it to the 'globalTags' plugin configuration or disabling the 'no-unknown-tag' rule.lit-plugin(no-unknown-tag-name)(2322)
```

Is there anything you could do to fix the above?

Kind regards,
Alex

**Comment by tomayac** [comment]
I think this will be resolved once https://github.com/GoogleChromeLabs/dark-mode-toggle/pull/38 lands. I’ll look into this after the weekend.

**Comment by aress31** [comment]
Great news, thanks @tomayac !

**Comment by tomayac** [comment]
Fixed with https://github.com/GoogleChromeLabs/dark-mode-toggle/pull/38.

**Comment by aress31** [comment]
@tomayac the latest update did not seem to solve this issue for me, please see:

![image](https://user-images.githubusercontent.com/11601622/92629238-ee607780-f2c5-11ea-9b2b-83c57e535f28.png)

```
Unknown tag <dark-mode-toggle>.
  Check that you've imported the element, and that it's declared on the HTMLElementTagNameMap. If it can't be imported, consider adding it to the 'globalTags' plugin configuration or disabling the 'no-unknown-tag' rule.lit-plugin(no-unknown-tag-name)(2322)
```

**Comment by tomayac** [comment]
@NotWoods I was under the assumption the [above problem](https://github.com/GoogleChromeLabs/dark-mode-toggle/issues/39#issuecomment-689691231) was resolved with https://github.com/GoogleChromeLabs/dark-mode-toggle/pull/38, and [these lines](https://github.com/NotWoods/dark-mode-toggle/blob/31634de11f5f73c5063b287406e0335f02bf4d42/src/dark-mode-toggle.d.ts#L58-L60) specifically. Is there anything @aress31 needs to do to make the warning go away? Sorry, I'm not a TypeScripter myself.

**Comment by NotWoods** [comment]
You may need to reference the dark mode module inside the same script, by doing one of:

```
import 'dark-mode-toggle'
/// <reference types="dark-mode-toggle" />
```

**Comment by aress31** [comment]
I can now confirm that the warning went away when updating `eslint-typescript`.

**Comment by tomayac** [comment]
Thanks, @NotWoods, for the help <3 and thanks, @aress31, for confirming this solved your issue.
